const DUMMY_DATA = [
  {
    id: 3077,
    businessId: 351,
    customerId: 79,
    status: 11,
    deliveryType: 1,
    createdAt: "2023-04-06 22:59:34",
    table: null,
    summary: {
      tax: 31.93,
      total: 252.2,
      discount: 13,
      deliveryPrice: 4.9,
      serviceFee: 0.3,
    },
    products: [
      {
        id: 7798,
        name: "2 burgers for 1",
        quantity: 26,
        price: 10,
        comment: null,
        options: [],
      },
    ],
    customer: {
      name: "John",
      lastName: "Doe",
      email: "john.doe@gmail.com",
      address: "Lapuankatu 4, NoWhere, Finland",
      addressNotes: "Call me when outside. Office next to K-Market.",
      phone: "123456789",
    },
    business: {
      id: 3077,
      order_id: 3077,
      name: "Juicy Burger",
      logo: "https://res.cloudinary.com/ordering2/image/upload/v1657563848/peperoni/yvrlciptrdvzarimuuj4.png",
      email: "hello@gomunchi.com",
      city_id: 4,
      address: "SomeWhereadb, No Where, Finland",
      address_notes: null,
      zipcode: null,
      cellphone: null,
      phone: "+3581234567890",
      location: {
        lat: 60.1710621,
        lng: 24.92966200000002,
        zipcode: -1,
        zoom: 15,
      },
      external_id: null,
      slug: "juicyburger",
      franchise_id: null,
      header:
        "https://res.cloudinary.com/ordering2/image/upload/v1694207450/peperoni/hxxbxoq3ucl3c1b3dyuu.png",
      pickup_time: "0:20",
      delivery_time: "0:20",
      available: true,
      city: {
        id: 4,
        name: "No Where",
        country_id: 1,
        administrator_id: 4,
        enabled: true,
      },
    },
  },
  {
    id: 3147,
    businessId: 351,
    customerId: 79,
    status: 15,
    deliveryType: 3,
    createdAt: "2023-04-17 20:29:41",
    table: 10,
    summary: {
      tax: 0.96,
      total: 8.1,
      discount: 0,
      deliveryPrice: 0,
      serviceFee: 0.3,
    },
    products: [
      {
        id: 9163,
        name: "Free fries when you spend over 10€",
        quantity: 2,
        price: 3.9,
        comment: null,
        options: [],
      },
    ],
    customer: {
      name: "John",
      lastName: "Doe",
      email: "John.Doe@gmail.com",
      address: "SomeWhereb, No Where, Finland",
      addressNotes: "Buzzer is broken, call me when you're outside. 3rd floor.",
      phone: "123456789",
    },
    business: {
      id: 3147,
      order_id: 3147,
      name: "Juicy Burger",
      logo: "https://res.cloudinary.com/ordering2/image/upload/v1657563848/peperoni/yvrlciptrdvzarimuuj4.png",
      email: "hello@gomunchi.com",
      city_id: 4,
      address: "SomeWhereb, No Where, Finland",
      address_notes: null,
      zipcode: null,
      cellphone: null,
      phone: "+3581234567890",
      location: {
        lat: 60.1710621,
        lng: 24.92966200000002,
        zipcode: -1,
        zoom: 15,
      },
      external_id: null,
      slug: "juicyburger",
      franchise_id: null,
      header:
        "https://res.cloudinary.com/ordering2/image/upload/v1694207450/peperoni/hxxbxoq3ucl3c1b3dyuu.png",
      pickup_time: "0:20",
      delivery_time: "0:20",
      available: true,
      city: {
        id: 4,
        name: "No Where",
        country_id: 1,
        administrator_id: 4,
        enabled: true,
      },
    },
  },
  {
    id: 3279,
    businessId: 351,
    customerId: 3951,
    status: 11,
    deliveryType: 1,
    createdAt: "2023-05-07 16:45:06",
    table: null,
    summary: {
      tax: 1.44,
      total: 17.9,
      discount: 0,
      deliveryPrice: 5.9,
      serviceFee: 0.3,
    },
    products: [
      {
        id: 7799,
        name: "Cheese burger",
        quantity: 3,
        price: 3.9,
        comment: null,
        options: [],
      },
    ],
    customer: {
      name: "Helen",
      lastName: "Li",
      email: "Helen.Li.ipad@icloud.com",
      address: "Kuortaneenkatu 1, No Where, Finland",
      addressNotes: null,
      phone: "400376076",
    },
    business: {
      id: 3279,
      order_id: 3279,
      name: "Juicy Burger",
      logo: "https://res.cloudinary.com/ordering2/image/upload/v1657563848/peperoni/yvrlciptrdvzarimuuj4.png",
      email: "hello@gomunchi.com",
      city_id: 4,
      address: "SomeWhereb, No Where, Finland",
      address_notes: null,
      zipcode: null,
      cellphone: null,
      phone: "+358123456789",
      location: {
        lat: 60.1710621,
        lng: 24.92966200000002,
        zipcode: -1,
        zoom: 15,
      },
      external_id: null,
      slug: "juicyburger",
      franchise_id: null,
      header:
        "https://res.cloudinary.com/ordering2/image/upload/v1694207450/peperoni/hxxbxoq3ucl3c1b3dyuu.png",
      pickup_time: "0:20",
      delivery_time: "0:20",
      available: true,
      city: {
        id: 4,
        name: "No Where",
        country_id: 1,
        administrator_id: 4,
        enabled: true,
      },
    },
  },
  {
    id: 3450,
    businessId: 351,
    customerId: 79,
    status: 15,
    deliveryType: 2,
    createdAt: "2023-05-20 11:00:28",
    table: null,
    summary: {
      tax: 2.7,
      total: 22.3,
      discount: 0,
      deliveryPrice: 0,
      serviceFee: 0.3,
    },
    products: [
      {
        id: 1998,
        name: "The original double",
        quantity: 1,
        price: 12,
        comment: null,
        options: [
          {
            id: 1293,
            name: "Size",
            image: null,
            suboptions: [
              {
                id: 4364,
                name: "Small",
                image: null,
                price: 10,
                position: "whole",
                quantity: 1,
              },
            ],
          },
        ],
      },
    ],
    customer: {
      name: "John",
      lastName: "Doe",
      email: "John.Doe@gmail.com",
      address: "SomeWhereb, No Where, Finland",
      addressNotes: "Buzzer is broken, call me when you're outside. 3rd floor.",
      phone: "123456789",
    },
    business: {
      id: 3450,
      order_id: 3450,
      name: "Juicy Burger",
      logo: "https://res.cloudinary.com/ordering2/image/upload/v1657563848/peperoni/yvrlciptrdvzarimuuj4.png",
      email: "hello@gomunchi.com",
      city_id: 4,
      address: "SomeWhereb, No Where, Finland",
      address_notes: null,
      zipcode: null,
      cellphone: null,
      phone: "+358123456789",
      location: {
        lat: 60.1710621,
        lng: 24.92966200000002,
        zipcode: -1,
        zoom: 15,
      },
      external_id: null,
      slug: "juicyburger",
      franchise_id: null,
      header:
        "https://res.cloudinary.com/ordering2/image/upload/v1694207450/peperoni/hxxbxoq3ucl3c1b3dyuu.png",
      pickup_time: "0:20",
      delivery_time: "0:20",
      available: true,
      city: {
        id: 4,
        name: "No Where",
        country_id: 1,
        administrator_id: 4,
        enabled: true,
      },
    },
  },
];

export { DUMMY_DATA };
